name: ci/cd for animating algorithms
on:
  push:
    branches: 
      -develop

jobs: 
  build: 
    runs-on: ubuntu-latest
  steps: 
      -uses: actions/checkout@v2
      -uses: actions/setup-node@v4
      with:
        node-version: 12
      run: yarn ci
      run: yarn build
      run: yarn deploy
